### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [hessnd/project2#1]
It looks like this isn't *quite* valid HTML. Link tags such as

``` html
<link rel="stylesheet" href="css/style.css">
```

should actually be in the `head` rather than `body` tag. Try updating your HTML files and make sure they don't return any errors when [uploaded to the W3C Validator](http://validator.w3.org/). Let me know when you've pushed up the update.

**Comment by hessnd** [comment]
I should of known that, I must not have been thinking.  I pushed the update and I didn't get any errors on the html validator.

**Comment by chrisvfritz** [comment]
:+1: Much better! And it's not a problem. We learn by making mistakes. :smiley:
